//USER REGISTER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

//USER LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//SET USER FROM LOCALSTORAGE
export const GET_USER_LOCALSTORAGE = 'GET_USER_LOCALSTORAGE';

//TOURNAMENTS BY USER
export const  TOURNAMENTS_BY_USER_REQUEST = "TOURNAMENTS_BY_USER_REQUEST";
export const  TOURNAMENTS_BY_USER_SUCCESS = "TOURNAMENTS_BY_USER_SUCCESS";
export const  TOURNAMENTS_BY_USER_FAILURE = "TOURNAMENTS_BY_USER_FAILURE";

//QUALIFITATION TOURNAMENT
export const  QUALIFITATION_TOURNAMENT_REQUEST = "QUALIFITATION_TOURNAMENT_REQUEST";
export const  QUALIFITATION_TOURNAMENT_SUCCESS = "QUALIFITATION_TOURNAMENT_SUCCESS";
export const  QUALIFITATION_TOURNAMENT_FAILURE = "QUALIFITATION_TOURNAMENT_FAILURE";

//MATCHES TOURNAMENT
export const  MATCHES_TOURNAMENT_REQUEST = "MATCHES_TOURNAMENT_REQUEST";
export const  MATCHES_TOURNAMENT_SUCCESS = "MATCHES_TOURNAMENT_SUCCESS";
export const  MATCHES_TOURNAMENT_FAILURE = "MATCHES_TOURNAMENT_FAILURE";

//EDIT MATCH TOURNAMENT
export const  EDIT_MATCH_TOURNAMENT_REQUEST = "EDIT_MATCH_TOURNAMENT_REQUEST";
export const  EDIT_MATCH_TOURNAMENT_SUCCESS = "EDIT_MATCH_TOURNAMENT_SUCCESS";
export const  EDIT_MATCH_TOURNAMENT_FAILURE = "EDIT_MATCH_TOURNAMENT_FAILURE";