// User register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// User login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Set user from localstorage
export const GET_USER_LOCALSTORAGE = 'GET_USER_LOCALSTORAGE';

// Tournaments by user
export const NEW_TOURNAMENT_REQUEST = "NEW_TOURNAMENT_REQUEST";
export const NEW_TOURNAMENT_SUCCESS = "NEW_TOURNAMENT_SUCCESS";
export const NEW_TOURNAMENT_FAILURE = "NEW_TOURNAMENT_FAILURE";

// New tournament
export const TOURNAMENTS_BY_USER_REQUEST = "TOURNAMENTS_BY_USER_REQUEST";
export const TOURNAMENTS_BY_USER_SUCCESS = "TOURNAMENTS_BY_USER_SUCCESS";
export const TOURNAMENTS_BY_USER_FAILURE = "TOURNAMENTS_BY_USER_FAILURE";


// Delete tournament
export const DELETE_TOURNAMENT_REQUEST = "DELETE_TOURNAMENT_REQUEST";
export const DELETE_TOURNAMENT_SUCCESS = "DELETE_TOURNAMENT_SUCCESS";
export const DELETE_TOURNAMENT_FAILURE = "DELETE_TOURNAMENT_FAILURE";

// Tournament´s teams
export const TEAMS_TOURNAMENT_REQUEST = "TEAMS_TOURNAMENT_REQUEST";
export const TEAMS_TOURNAMENT_SUCCESS = "TEAMS_TOURNAMENT_SUCCESS";
export const TEAMS_TOURNAMENT_FAILURE = "TEAMS_TOURNAMENT_FAILURE";

// New team
export const NEW_TEAM_REQUEST = "NEW_TEAM_REQUEST";
export const NEW_TEAM_SUCCESS = "NEW_TEAM_SUCCESS";
export const NEW_TEAM_FAILURE = "NEW_TEAM_FAILURE";

// Tournament´s qualification
export const QUALIFITATION_TOURNAMENT_REQUEST = "QUALIFITATION_TOURNAMENT_REQUEST";
export const QUALIFITATION_TOURNAMENT_SUCCESS = "QUALIFITATION_TOURNAMENT_SUCCESS";
export const QUALIFITATION_TOURNAMENT_FAILURE = "QUALIFITATION_TOURNAMENT_FAILURE";

// Tournament´s matches
export const MATCHES_TOURNAMENT_REQUEST = "MATCHES_TOURNAMENT_REQUEST";
export const MATCHES_TOURNAMENT_SUCCESS = "MATCHES_TOURNAMENT_SUCCESS";
export const MATCHES_TOURNAMENT_FAILURE = "MATCHES_TOURNAMENT_FAILURE";

// Edit a tournament´s match
export const EDIT_MATCH_TOURNAMENT_REQUEST = "EDIT_MATCH_TOURNAMENT_REQUEST";
export const EDIT_MATCH_TOURNAMENT_SUCCESS = "EDIT_MATCH_TOURNAMENT_SUCCESS";
export const EDIT_MATCH_TOURNAMENT_FAILURE = "EDIT_MATCH_TOURNAMENT_FAILURE";