//USER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_USER_LOCALSTORAGE = 'GET_USER_LOCALSTORAGE';

export const  TOURNAMENTS_BY_USER_REQUEST = "TOURNAMENTS_BY_USER_REQUEST";
export const  TOURNAMENTS_BY_USER_SUCCESS = "TOURNAMENTS_BY_USER_SUCCESS";
export const  TOURNAMENTS_BY_USER_FAILURE = "TOURNAMENTS_BY_USER_FAILURE";